name: spring backend auto deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git repository 가져오기
        uses: actions/checkout@v3

      - name: JDK 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드
        run: ./gradlew clean build

      - name: Docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USER }}/spring-test:mixed .

      - name: DockerHub 로그인
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Docker 이미지 푸시
        run: docker push ${{ secrets.DOCKER_USER }}/spring-test:mixed

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: EC2에 SSH 접속하여 백엔드 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop backend || true
            docker rm backend || true
            docker rmi ${{ secrets.DOCKER_USER }}/spring-test:mixed || true
            docker pull ${{ secrets.DOCKER_USER }}/spring-test:mixed
            docker run -d -p 8080:8080 --name backend ${{ secrets.DOCKER_USER }}/spring-test:mixed
